#include<stdio.h>
#include"help.h"
const char* help = 
    "--- Help ---\n\r"
    "[h]        : This message\n\r"
    "[Shift+h]  : Show math function help\n\r"
    "[i]        : Move cursor left\n\r"
    "[o]        : Move cursor right\n\r"
    "[Backspace]: Delete character\n\r"
    "[Shift+o]  : Calculate result\n\r"
    "[Esc]      : Exit (Intentionatly works with esc sequences)\n\r"
    "\n\r"
    "--- Basic math stuff ---\n\r"
    "0-9        : Numbers\n\r"
    "p          : π constant\n\r"
    "+, -, *, / : Standard arithmetic\n\r"
    "^          : Power\n\r"
    "( )        : Parentheses\n\r"
    "\n\r"
    "Start typing to start typing...\n\r";
const char* functions_help = 
    "--- Math Functions ---\n\r"
    "\n\r"
    "Key | Displayed | Description\n\r"
    "----|-----------|----------------------\n\r"
    " !  | !         | Factorial\n\r"
    " s  | sine      | Sine\n\r"
    " S  | asin      | Arcsine\n\r"
    " c  | cosi      | Cosine\n\r"
    " C  | acos      | Arccosine\n\r"
    " t  | tang      | Tangent\n\r"
    " T  | atan      | Arctangent\n\r"
    " e  | expo      | Exponential (e^x)\n\r"
    " r  | sqrt      | Square Root\n\r"
    " R  | cbrt      | Cube Root\n\r"
    " a  | absl      | Absolute Value\n\r"
    " A  | sign      | Sign of x\n\r"
    "\n\r"
    "Pressing function key will add open parenthesis after it.\n\r"
    "Functions' display names are exactly 4 chars because im lazy :).";